---

services:
  indexer:
    build:
      context: ../../indexer
    environment:
      - MAINCHAIN_URL=${MAINCHAIN_URL:-ws://archive-node:9944}
      - ARGON_CHAIN=${ARGON_CHAIN:-dev-docker}
      - DB_DIR=${DB_DIR:-/indexer}
      - PORT=3262
    restart: on-failure
    ports:
      - "0:3262"
    volumes:
      - indexer-data:/indexer
volumes:
  indexer-data:
